---
- name: Create Mysql user
  community.mysql.mysql_user:
    login_host: 'localhost'
    login_user: root
    login_password: root
    name: "{{ wp_mysql_user }}" 
    password: "{{ wp_mysql_password }}"
    #priv: "*.*:ALL"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create Mysql database
  community.mysql.mysql_db:
    login_host: 'localhost'
    login_user: root
    login_password: root
    name: "{{ wp_mysql_db }}"
    state: present
 
  