---
- name: Installing dependencies or (PHP)
  ansible.builtin.apt:
    name: 
      - php
      - php-bcmath
      - php-curl
      - php-imagick
      - php-intl
      - php-json
      - php-mbstring
      - php-mysql
      - php-xml
      - php-zip
     
    state: latest 
    update_cache: yes
  
    
 # become: true
